<template>
  <div class="page-wrap"><page-section title="移动应用配置"><template slot="extra"><el-button size="small" type="primary" @click="openCreate">新增应用</el-button></template>
    <el-form :inline="true" size="small" @submit.native.prevent><el-form-item label="项目"><el-select v-model="projectId" filterable clearable placeholder="全部项目" style="width:220px"><el-option v-for="item in projects" :key="item.id" :label="item.name" :value="String(item.id)" /></el-select></el-form-item><el-form-item><el-button type="primary" @click="fetchList">查询</el-button></el-form-item></el-form>
    <el-table v-loading="loading" :data="rows" border style="width:100%;"><el-table-column prop="name" label="应用名称" min-width="150" /><el-table-column label="项目" min-width="120"><template slot-scope="scope">{{ projectName(scope.row.project_id) }}</template></el-table-column><el-table-column prop="package_name" label="包名" min-width="220" show-overflow-tooltip /><el-table-column prop="launch_activity" label="启动 Activity" min-width="200" show-overflow-tooltip /><el-table-column label="执行前" width="150"><template slot-scope="scope">{{ scope.row.install_before_run ? '安装 ' : '' }}{{ scope.row.clear_data_before_run ? '清数据' : '' }}{{ !scope.row.install_before_run && !scope.row.clear_data_before_run ? '-' : '' }}</template></el-table-column><el-table-column label="状态" width="90"><template slot-scope="scope"><el-tag size="mini" :type="scope.row.enabled ? 'success' : 'info'">{{ scope.row.enabled ? '启用' : '停用' }}</el-tag></template></el-table-column><el-table-column label="操作" width="100" fixed="right"><template slot-scope="scope"><el-button type="text" @click="openEdit(scope.row)">编辑</el-button></template></el-table-column></el-table>
    <el-dialog :title="form.id ? '编辑应用' : '新增应用'" :visible.sync="dialogVisible" width="560px" :close-on-click-modal="false"><el-form ref="form" :model="form" :rules="rules" label-width="110px" size="small"><el-form-item label="项目" prop="project_id"><el-select v-model="form.project_id" filterable placeholder="选择项目" style="width:100%"><el-option v-for="item in projects" :key="item.id" :label="item.name" :value="item.id" /></el-select></el-form-item><el-form-item label="应用名称" prop="name"><el-input v-model.trim="form.name" /></el-form-item><el-form-item label="包名" prop="package_name"><el-input v-model.trim="form.package_name" /></el-form-item><el-form-item label="启动 Activity"><el-input v-model.trim="form.launch_activity" /></el-form-item><el-form-item label="APK 受控路径"><el-input v-model.trim="form.apk_path" /></el-form-item><el-form-item label="版本名称"><el-input v-model.trim="form.version_name" /></el-form-item><el-form-item label="版本号"><el-input v-model.trim="form.version_code" /></el-form-item><el-form-item label="执行选项"><el-checkbox v-model="form.install_before_run">执行前安装</el-checkbox><el-checkbox v-model="form.clear_data_before_run">执行前清数据</el-checkbox><el-checkbox v-model="form.enabled">启用</el-checkbox></el-form-item></el-form><div slot="footer"><el-button @click="dialogVisible=false">取消</el-button><el-button type="primary" :loading="saving" @click="save">保存</el-button></div></el-dialog>
  </page-section></div>
</template>
<script>
import PageSection from '@/components/TestPlatform/common/PageSection'
import { getProjectList } from '@/api/projectApi'
import { createMobileApp, getMobileAppList, updateMobileApp } from '@/api/mobileAutomationApi'
export default { name:'MobileAutomationAppList', components:{PageSection}, data(){return {loading:false,saving:false,dialogVisible:false,rows:[],projects:[],projectId:'',form:{},rules:{project_id:[{required:true,message:'请选择项目',trigger:'change'}],name:[{required:true,message:'请输入应用名称',trigger:'blur'}],package_name:[{required:true,message:'请输入包名',trigger:'blur'}]}}}, created(){this.loadProjects();this.fetchList()}, methods:{dataOf(res){return (res&&res.data)||res||{}},loadProjects(){return getProjectList({pageNo:1,pageSize:500}).then(res=>{const d=this.dataOf(res);this.projects=d.list||d.items||[]})},fetchList(){this.loading=true;getMobileAppList(this.projectId?{project_id:this.projectId}:{}).then(res=>{this.rows=this.dataOf(res).list||[]}).finally(()=>{this.loading=false})},projectName(id){const item=this.projects.find(v=>String(v.id)===String(id));return item?item.name:id||'-'},emptyForm(){return {project_id:'',name:'',package_name:'',launch_activity:'',apk_path:'',version_name:'',version_code:'',install_before_run:false,clear_data_before_run:false,enabled:true}},openCreate(){this.form=this.emptyForm();this.dialogVisible=true},openEdit(row){this.form=Object.assign(this.emptyForm(),row,{install_before_run:!!row.install_before_run,clear_data_before_run:!!row.clear_data_before_run,enabled:!!row.enabled});this.dialogVisible=true},save(){this.$refs.form.validate(valid=>{if(!valid)return;this.saving=true;const fn=this.form.id?updateMobileApp:createMobileApp;fn(this.form).then(()=>{this.$message.success('应用配置已保存');this.dialogVisible=false;this.fetchList()}).finally(()=>{this.saving=false})})}} }
</script>
